#!/bin/sh

REV=$(git rev-parse --verify HEAD)

# the quick style check should have passed to reach this point
git notes --ref lint add -f -m "pass" "$REV" 1>/dev/null

# queue the commit for a local test
sh -c "$(git rev-parse --git-dir)/../.hooks/verify test $REV" &
