#!/bin/sh

# remove previous result
git notes --ref quickcheck remove "$(git rev-list --max-parents=0 HEAD)" 1>/dev/null 2>&1

# run a quick style check in the background
sh -c "$(git rev-parse --git-dir)/../.hooks/verify quick" &

exit 0